Matrix_Test/Matrix_Test/Models/License.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Matrix_Test.Models
{
    public class License
    {
        public string key { get; set; }
        public string name { get; set; }
        public string spdx_id { get; set; }
        public string url { get; set; }
        public string node_id { get; set; }
    }
}

Matrix_Test/Matrix_Test/Models/Repo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Matrix_Test.Models
{
    public class Item
    {
        public int id { get; set; }
        public string node_id { get; set; }
        public string name { get; set; }
        public string full_name { get; set; }
        public bool @private { get; set; }
        public Owner owner { get; set; }
        public string html_url { get; set; }
        public string description { get; set; }
        public bool fork { get; set; }
        public string url { get; set; }
        public string forks_url { get; set; }
        public string keys_url { get; set; }
        public string collaborators_url { get; set; }
        public string teams_url { get; set; }
        public string hooks_url { get; set; }
        public string issue_events_url { get; set; }
        public string events_url { get; set; }
        public string assignees_url { get; set; }
        public string branches_url { get; set; }
        public string tags_url { get; set; }
        public string blobs_url { get; set; }
        public string git_tags_url { get; set; }
        public string git_refs_url { get; set; }
        public string trees_url { get; set; }
        public string statuses_url { get; set; }
        public string languages_url { get; set; }
        public string stargazers_url { get; set; }
        public string contributors_url { get; set; }
        public string subscribers_url { get; set; }
        public string subscription_url { get; set; }
        public string commits_url { get; set; }
        public string git_commits_url { get; set; }
        public string comments_url { get; set; }
        public string issue_comment_url { get; set; }
        public string contents_url { get; set; }
        public string compare_url { get; set; }
        public string merges_url { get; set; }
        public string archive_url { get; set; }
        public string downloads_url { get; set; }
        public string issues_url { get; set; }
        public string pulls_url { get; set; }
        public string milestones_url { get; set; }
        public string notifications_url { get; set; }
        public string labels_url { get; set; }
        public string releases_url { get; set; }
        public string deployments_url { get; set; }
        public DateTime created_at { get; set; }
        public DateTime updated_at { get; set; }
        public DateTime pushed_at { get; set; }
        public string git_url { get; set; }
        public string ssh_url { get; set; }
        public string clone_url { get; set; }
        public string svn_url { get; set; }
        public string homepage { get; set; }
        public int size { get; set; }
        public int stargazers_count { get; set; }
        public int watchers_count { get; set; }
        public string language { get; set; }
        public bool has_issues { get; set; }
        public bool has_projects { get; set; }
        public bool has_downloads { get; set; }
        public bool has_wiki { get; set; }
        public bool has_pages { get; set; }
        public int forks_count { get; set; }
        public object mirror_url { get; set; }
        public bool archived { get; set; }
        public bool disabled { get; set; }
        public int open_issues_count { get; set; }
        public License license { get; set; }
        public int forks { get; set; }
        public int open_issues { get; set; }
        public int watchers { get; set; }
        public string default_branch { get; set; }
        public double score { get; set; }
    }


}

Matrix_Test/Matrix_Test/Models/RepoOwner.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Matrix_Test.Models
{
    public class Owner
    {
        public string login { get; set; }
        public int id { get; set; }
        public string node_id { get; set; }
        public string avatar_url { get; set; }
        public string gravatar_id { get; set; }
        public string url { get; set; }
        public string html_url { get; set; }
        public string followers_url { get; set; }
        public string following_url { get; set; }
        public string gists_url { get; set; }
        public string starred_url { get; set; }
        public string subscriptions_url { get; set; }
        public string organizations_url { get; set; }
        public string repos_url { get; set; }
        public string events_url { get; set; }
        public string received_events_url { get; set; }
        public string type { get; set; }
        public bool site_admin { get; set; }
    }
}

Matrix_Test/Matrix_Test/Models/RepoResults.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Matrix_Test.Models
{
    public class RepoResults
    {
        public int total_count { get; set; }
        public bool incomplete_results { get; set; }
        public IEnumerable<Item> items { get; set; }
    }
}

Matrix_Test/Matrix_Test/Controllers/BookMarkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Matrix_Test.Controllers
{
    public class BookMarkController : Controller
    {
        // GET: BookMark
        public ActionResult Index()
        {
            if (Session["bookMarkList"] != null)
            {
                return View(Session["bookMarkList"]);
            }
            return View();
        }
    }
}

Matrix_Test/Matrix_Test/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Matrix_Test.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

    }
}

Matrix_Test/Matrix_Test/Controllers/SearchResultsController.cs
using Matrix_Test.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Matrix_Test.Controllers
{
    public class SearchResultsController : Controller
    {
        public RepoSerarch search = new RepoSerarch();

        // GET: SearchResults
        public async Task<ActionResult> Index(string searchValue)
        {
            if (searchValue != null)
            {
                RepoResults repoResults = new RepoResults();
                // Start the search function 
                repoResults = await search.Start("repositories?q=" + searchValue); 

                return View(repoResults.items);
            }
            return RedirectToAction("Index", "Home");
        }

        // post: Item
        // Save item to Session at 'bookMarkList' 
        [HttpPost]
        public ActionResult saveRepoToSession(Item repo)
        {
            if (Request.IsAjaxRequest())
            {
                if (Session["bookMarkList"] == null)
                {
                    Session["bookMarkList"] = new List<Item>();
                }
                List<Item> itemList = Session["bookMarkList"] as List<Item>;
                itemList.Add(repo);
                Session["bookMarkList"] = itemList;

                return RedirectToAction("Index", "BookMark");
            }
            return new EmptyResult();
        }


    }
}

Matrix_Test/Matrix_Test/Views/BookMark/Index.cshtml
@model IEnumerable<Matrix_Test.Models.Item>

<!-- Book Mark Page - Show all saved repo from the Session -->

<div class="container">
    <div class="text-center p-3">
        <h1 style="color:#ea4164">BookMark list</h1>
    </div>
    <div class="row">
        @{
            if (Model != null)
            {
                foreach (var item in Model)
                {
                    <div class="text-center col-sm-4 p-2 ">
                        @{
                            Html.RenderPartial("_itemView", item);  // Render the Repo Partial View
                        }
                    </div>
                }
            }
            else
            {
                <div class="text-center col-sm-12">
                    <h3>
                        <i class="text-light">No bookmarks yet..</i>
                    </h3>
                </div>
            }
        }
    </div>
</div>

Matrix_Test/Matrix_Test/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<style>
    .scroll-wrapper {
        overflow-x: scroll hidden;
        overflow-y: hidden;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
    }

    .scroll-item {
        display: inline-block;
    }
</style>

<!-- Home Page - search option and bookmark view list -->

<div>
    <!-- Search bar -->
    <div class="home-page-top">
        <div class="text-center">
            <img src="~/Content/assets/github_logo_pink.png" width="150" />
            <h2>Repositories Search Application</h2>
            <h4 style="color:#ea4164">Enter technology or some text..</h4>
        </div>
        <div>
            @using (Html.BeginForm("Index", "SearchResults"))
            {
                <div>
                    <input style="color: black" class="search-input" type="search" name="searchValue" placeholder="Enter text here.." />
                </div>
                <div class="p-2">
                    <input class="btn bg-basic" type="submit" value="Search" />
                </div>
            }
        </div>
    </div>

    <hr />

    <!-- Bookmark List -->
    <div>

        <div class="text-center p-3">
            <h2 style="color:#ea4164">Bookmark Repositories List</h2>
        </div>
        <div class="scroll-wrapper p-3">
            @{
                if (Session["bookMarkList"] != null)
                {
                    foreach (var item in Session["bookMarkList"] as List<Matrix_Test.Models.Item>)
                    {
                        <div class="scroll-item w-25 text-center p-3">
                            @{
                                Html.RenderPartial("_itemView", item);  // Render the Repo Partial View
                            }
                        </div>
                    }
                }
                else
                {
                    <div class="text-center">
                        <h3>
                            <i class="text-light">No bookmarks yet..</i>
                        </h3>
                    </div>
                }
            }
        </div>
    </div>
</div>

Matrix_Test/Matrix_Test/Views/SearchResults/Index.cshtml
@model IEnumerable<Matrix_Test.Models.Item>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Search Results Page - new search button and search results view -->


<div class="container">
    <div class="text-center">
        <h2 style="color:white">Search Results</h2>
        <h4 style="color: #ea4164">Total Results: @Model.Count()</h4>
    </div>
    <div class="p-3 text-center">
        <button id="linker" style="color:white" class="btn bg-basic">
            @Html.ActionLink("New Search", "Index", "Home")
        </button>
    </div>
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="text-center col-sm-4 p-2 ">
                @{

                    Html.RenderPartial("_itemView", item);  // Render the Repo Partial View
                }
            </div>
        }
    </div>
</div>

Matrix_Test/Matrix_Test/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Sagiv Mor ASP.NET Application</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @{
        Html.RenderPartial("_headerNavBar");  // Render the NavBar Partial View
    }
    <div class="body-content">
        @RenderBody()
        <hr /> 
        <footer class="text-center">
            <p class="text-white">&copy; @DateTime.Now.Year - Sagiv Mor, Repo Search Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Matrix_Test/Matrix_Test/Views/Shared/_headerNavBar.cshtml
<!-- Navbar - Partial view for all pages-->

<nav class="navbar navbar-expand-lg navbar-dark bg-dark navbar-fixed-top">
    <div class="container">
        <a class="navbar-brand">
            <img src="~/Content/assets/github_logo_pink.png" width="30" class="d-inline-block align-top" alt="">
        </a>
        @Html.ActionLink("Repo Search", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Bookmarks", "Index", "BookMark", new { area = "" }, new { @class = "nav-link text-info" })
                </li>
            </ul>
        </div>
    </div>
</nav>

Matrix_Test/Matrix_Test/Views/Shared/_itemView.cshtml
@using Matrix_Test.Models
@model Item

<!--Add function to add repo to bookmarks list-->
<script type="text/javascript">
    function add(obj) {
        console.log(obj)
        $.ajax({
            url: '@Url.Action("saveRepoToSession")',
            type: 'POST',
            data: JSON.stringify(obj),
            dataType: 'json',
            processData: false,
            contentType: 'application/json; charset=utf-8',
            success: function (data) {
                console.warn("success");
            },
        })
        alert("added to bookmarks");
 }
</script>


<!--Item - Repo results from the API-->
<div class="white-box p-3">
    <div>
        <h1 style="color:white">@Html.DisplayFor(modelItem => Model.name)</h1>
        <h4 style="color: #ea4164">@Html.DisplayFor(modelItem => Model.full_name)</h4>
    </div>
    <div>
        <div>
            <img class="avatar-img" src="@Html.DisplayFor(modelItem => Model.owner.avatar_url)" />
        </div>
        <div>
            @* @Html.DisplayFor(modelItem => item.description)*@
            <h6 style="color:white;"><u></u></h6>
            <div class="p-2">
                <button class="btn text-white">
                    <a href="@Html.DisplayFor(modelItem => Model.html_url)">Go to</a>
                </button>

                @{
                    if (Request.Url.GetLeftPart(UriPartial.Path).IndexOf("SearchResults") != -1)
                    {
                        <button id="myLink" class="btn bg-basic" onclick="add(@Html.Raw(Json.Encode(Model)).ToString())">save</button>
                    }
                }

            </div>
        </div>
    </div>
</div>